# Generated by Django 5.2.4 on 2025-08-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('marks', models.TextField()),
                ('branch', models.TextField()),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
