# Generated by Django 5.2.4 on 2025-09-01 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AadharDetails',
            fields=[
                ('aadhar_number', models.BigAutoField(default=878468687591, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('phone', models.PositiveBigIntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('photo', models.ImageField(upload_to='pics')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gender')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.state')),
            ],
        ),
    ]
