# Generated by Django 5.2.4 on 2025-09-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhardetails',
            name='aadhar_number',
        ),
        migrations.AddField(
            model_name='aadhardetails',
            name='number',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
