# Generated by Django 5.2.4 on 2025-09-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_aadhardetails_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhardetails',
            name='number',
            field=models.BigAutoField(default=878468687591, primary_key=True, serialize=False),
        ),
    ]
