# Generated by Django 5.2.4 on 2025-09-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_aadhardetails_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhardetails',
            name='number',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
