# Generated by Django 5.2.4 on 2025-09-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_aadhardetails_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aadhardetails',
            old_name='number',
            new_name='Aadhar_number',
        ),
    ]
