from django.urls import path
from . import views

urlpatterns = [
    path('bedlinen',views.bedlinen),
    path('bedrunners',views.bedrunners),
    path('matress',views.matress),
    path('bedsheets',views.bedsheets),
    path('beddingsets',views.beddingsets),
    path('blankets',views.blankets),
    path('pillows',views.pillows),
    path('bedcovers',views.bedcovers),
    path('diwansets',views.diwansets),
    path('chairpads',views.chairpads),
    path('sofacovers',views.sofacovers),
    path('flooring',views.flooring),
    path('floorrunners',views.floorrunners),
    path('carpets',views.carpets),
    path('floormats',views.floormats),
    path('doormats',views.doormats),
    path('bath',views.bath),
    path('bathtowels',views.bathtowels),
    path('handfacetowels',views.handfacetowels),
    path('beachtowels',views.beachtowels),
    path('towelsets',views.towelsets),
    path('bathrugs',views.bathrugs),
    path('bathrobes',views.bathrobes),
    path('bathroomaccessories',views.bathroomaccessories),
    path('showercurtains',views.showercurtains),
    path('lampslighting',views.lampslighting),
    path('floorlamps',views.floorlamps),
    path('cielinglamps',views.ceilinglamps),
    path('tablelamps',views.tablelamps),
    path('walllamps',views.walllamps),
]
