# Generated by Django 5.2.4 on 2025-08-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('role', models.CharField(max_length=30)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('doj', models.DateField()),
                ('experience', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
