from  django.urls import path
from . import views

urlpatterns=[
    path("2",views.men),
    path("3",views.tshirts),
    path("4",views.casual),
    path("5",views.formal),
    path("6",views.Sweatshirts),
    path("7",views.Sweaters),
    path("8",views.Jackets),
    path("9",views.Blazers),
    path("10",views.MenSuits),
    path("11",views.RainJackets),
    path("12",views.indians),
    path("13",views.Kurtas),
    path("14",views.Sherwanis),
    path("15",views.NehruJackets),
    path("16",views.Dhotis),
    path("17",views.Jeans),
    path("18",views.Trousers),
    path("19",views.FormalTrousers),
    path("20",views.Shorts),
    path("21",views.TrackPants),
    path("22",views.CasualShoes),
    path("23",views.SportsShoes),
    path("24",views.FormalShoes),
    path("25",views.Sneakers),
    path("26",views.Sandals),
    path("27",views.FlipFlops),
    path("28",views.Socks),
    path("29",views.PersonalCare),
    path("30",views.Sunglasses ),
    path("31",views.Watches),
    path("32",views.Sports),
]
