# Generated by Django 5.2.4 on 2025-10-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('Branch', models.CharField()),
                ('Age', models.IntegerField()),
                ('Marks', models.IntegerField()),
                ('Address', models.CharField()),
            ],
        ),
    ]
