# Generated by Django 5.2.4 on 2025-10-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('branch', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('address', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
